### ISSUE TITLE
Bug: Success sended message in danger color if previus send failed.

### ISSUE THREAD

**Issue by technoboyz** [albx/ProposalCollector#15]
File: ProposalCollector/ProposalCollector.Client/Pages/Index.razor
Linea: 66
Aggiungere: isError = false;
Motivo:
Se in un primo tentativo produci un errore (Es: descrizione troppo lunga), quando nel secondo invio tutto va a buon fine, quella variabile resta su true generando un messaggio in "alert-danger" e non in "alert-success".
Inoltre è preferibile impostare nel campo input della descrizione l'attributo maxlength che previene l'errore di troncamento ricevuto dal database.

**Comment by albx** [comment]
@technoboyz grazie mille!
Messa in backlog :)
